macro(Smart_List_Append list_to_append var_to_append)
    message(STATUS "macro:" "${list_to_append}" "${var_to_append}")
    if ( NOT( "${var_to_append}" IN_LIST "${list_to_append}" ) )
        message(STATUS "macro if:" "${list_to_append}")
        list(APPEND list_to_append "${var_to_append}")
        set(list_to_append "${list_to_append}" PARENT_SCOPE)
    endif()
    message(STATUS "macro over:" "${list_to_append}")
endmacro()
